### PR TITLE
Updating example app to include .env config loading

### PR DESCRIPTION
**Pull request by babus**
The example was lacking demonstration of how environment variables can override the yaml configs. I have added a .env file and using `godotenv` to load them first.

### CODE REVIEW

**Comment by ilyakaznacheev** [comment]
Thank you for the PR.

Also, the example is about reading from the `.yml` file and an environment, not from `.env` file (according to the documentation).

In fact, `cleanenv` can load `.env` files by itself, so such an example may confuse users.

So, you can add another example into a new example directory about reading from the `.env` file.

Also, take a look at example tests in [godoc](https://pkg.go.dev/github.com/ilyakaznacheev/cleanenv?tab=doc), they cover a lot of such features.

**Comment by paracha3** [comment]
i would prefer no external dependencies

**Comment by ilyakaznacheev** [comment]
@paracha3 agree, it makes sense too

**Comment by ilyakaznacheev** [comment]
Closed because we don't want this in the library. But thank you for your contribution anyway.

**Pull request closed without merging**
